name: scheduler_app
description: A scheduling app for team availability and leader selection.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  provider: ^6.1.1
  intl: ^0.20.2
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
  - assets/logos_150px_WCC-Original-White.png
  - assets/Google_Icons-09-512.webp
  - assets/WCC-Responsive-White.png
  - assets\animations\hand_point.json
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#2A2A3D"
  image: assets/WCC-Responsive-White.png
  android: true
  ios: true