// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vKcK_IziEJx9WLQzWwpfNUcsSKOH14Q',
    appId: '1:336881946339:web:ef47be25614150c29a7fd6',
    messagingSenderId: '336881946339',
    projectId: 'wcc-scheduling',
    authDomain: 'wcc-scheduling.firebaseapp.com',
    storageBucket: 'wcc-scheduling.firebasestorage.app',
    measurementId: 'G-THTRCGTGER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhr5zuYqIpnzCyZ3-RHzE5Te0_yqYcipY',
    appId: '1:336881946339:android:dc06dfeb4587b2ae9a7fd6',
    messagingSenderId: '336881946339',
    projectId: 'wcc-scheduling',
    storageBucket: 'wcc-scheduling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPu8HZyKV-hYYnad27DXmxM6TnzDSymnc',
    appId: '1:336881946339:ios:0111a867f76e4ec39a7fd6',
    messagingSenderId: '336881946339',
    projectId: 'wcc-scheduling',
    storageBucket: 'wcc-scheduling.firebasestorage.app',
    androidClientId: '336881946339-h7rbbi6m8bnvilg6aqnvjli4up38c482.apps.googleusercontent.com',
    iosClientId: '336881946339-ecf8v4rgpruj288tdltqjgiqib46foak.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedulerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPu8HZyKV-hYYnad27DXmxM6TnzDSymnc',
    appId: '1:336881946339:ios:0111a867f76e4ec39a7fd6',
    messagingSenderId: '336881946339',
    projectId: 'wcc-scheduling',
    storageBucket: 'wcc-scheduling.firebasestorage.app',
    androidClientId: '336881946339-h7rbbi6m8bnvilg6aqnvjli4up38c482.apps.googleusercontent.com',
    iosClientId: '336881946339-ecf8v4rgpruj288tdltqjgiqib46foak.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedulerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vKcK_IziEJx9WLQzWwpfNUcsSKOH14Q',
    appId: '1:336881946339:web:0b8affa5d775bf0e9a7fd6',
    messagingSenderId: '336881946339',
    projectId: 'wcc-scheduling',
    authDomain: 'wcc-scheduling.firebaseapp.com',
    storageBucket: 'wcc-scheduling.firebasestorage.app',
    measurementId: 'G-N3SLTGXH0Z',
  );
}
